
all: 1-1.out 1-2.out 1-3.out 1-4.out \
     1-5.out 1-6.out 1-7.out

1-1.out:	1-1.c 
	gcc $< -o $@

1-2.out:	1-2.c 
	gcc $< -o $@

1-3.out:	1-3.c
	gcc $< -o $@

1-4.out:	1-4.c
	gcc $< -o $@

1-5.out:	1-5.c
	gcc $< -o $@

1-6.out:	1-6.c
	gcc $< -o $@

1-7.out:	1-7.c
	gcc $< -o $@



clean: 
	rm -rf *.out
